INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 1', 'cloth-item-1', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 2', 'perfume-2', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 3', 'cloth-item-3', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 4', 'cloth-item-4', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 5', 'cloth-item-5', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 6', 'perfume-6', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 7', 'cloth-item-7', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 8', 'cloth-item-8', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 9', 'cloth-item-9', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 10', 'cloth-item-10', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 11', 'perfume-11', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 12', 'perfume-12', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 13', 'cloth-item-13', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 14', 'cloth-item-14', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 15', 'cloth-item-15', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 16', 'perfume-16', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 17', 'cloth-item-17', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 18', 'cloth-item-18', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 19', 'cloth-item-19', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 20', 'cloth-item-20', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 21', 'perfume-21', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 22', 'perfume-22', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 23', 'perfume-23', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 24', 'perfume-24', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 25', 'cloth-item-25', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 26', 'perfume-26', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 27', 'cloth-item-27', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 28', 'cloth-item-28', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 29', 'cloth-item-29', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 30', 'perfume-30', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 31', 'cloth-item-31', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 32', 'perfume-32', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 33', 'perfume-33', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 34', 'cloth-item-34', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 35', 'perfume-35', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 36', 'perfume-36', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 37', 'perfume-37', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 38', 'perfume-38', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 39', 'cloth-item-39', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 40', 'cloth-item-40', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 41', 'cloth-item-41', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 42', 'perfume-42', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 43', 'cloth-item-43', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 44', 'perfume-44', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 45', 'cloth-item-45', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 46', 'cloth-item-46', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 47', 'cloth-item-47', 'Стильная одежда', 'cloth');
INSERT INTO products (name, url, description, product_type) VALUES ('Perfume 48', 'perfume-48', 'Аромат высокого качества', 'parfume');
INSERT INTO products (name, url, description, product_type) VALUES ('Cloth Item 49', 'cloth-item-49', 'Стильная одежда', 'cloth');
INSERT INTO product_photos (product_id, photo_url, position) VALUES (1, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (2, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (3, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (4, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (5, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (6, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (7, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (8, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (9, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (10, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (11, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (12, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (13, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (14, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (15, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (16, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (17, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (18, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (19, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (20, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (21, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (22, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (23, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (24, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (25, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (26, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (27, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (28, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (29, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (30, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (31, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (32, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (33, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (34, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (35, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (36, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (37, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (38, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (39, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (40, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (41, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (42, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (43, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (44, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (45, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (46, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (47, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (48, 'statics/img/product_img/12.png', 0);
INSERT INTO product_photos (product_id, photo_url, position) VALUES (49, 'statics/img/product_img/12.png', 0);
INSERT INTO product_variants (product_id, value, price, unit) VALUES (1, 42, 6004, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (1, 44, 9654, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (1, 46, 5316, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (1, 48, 8442, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (2, 30, 9399, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (2, 50, 6056, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (2, 100, 11089, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (3, 42, 8238, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (3, 44, 5079, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (3, 46, 10371, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (3, 48, 7025, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (4, 42, 6752, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (4, 44, 7923, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (4, 46, 11343, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (4, 48, 8436, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (5, 42, 9581, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (5, 44, 3080, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (5, 46, 7392, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (5, 48, 9120, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (6, 30, 9531, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (6, 50, 11617, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (6, 100, 3820, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (7, 42, 7743, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (7, 44, 11134, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (7, 46, 7642, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (7, 48, 7818, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (8, 42, 8694, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (8, 44, 11948, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (8, 46, 10154, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (8, 48, 10848, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (9, 42, 11858, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (9, 44, 8097, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (9, 46, 11892, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (9, 48, 5404, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (10, 42, 3928, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (10, 44, 5886, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (10, 46, 7689, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (10, 48, 9773, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (11, 30, 11002, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (11, 50, 5890, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (11, 100, 7876, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (12, 30, 5085, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (12, 50, 8255, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (12, 100, 11277, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (13, 42, 9990, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (13, 44, 10308, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (13, 46, 6542, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (13, 48, 5005, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (14, 42, 9833, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (14, 44, 9746, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (14, 46, 7606, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (14, 48, 3440, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (15, 42, 8177, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (15, 44, 3701, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (15, 46, 11555, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (15, 48, 8940, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (16, 30, 5360, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (16, 50, 11020, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (16, 100, 4758, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (17, 42, 4977, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (17, 44, 4455, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (17, 46, 10819, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (17, 48, 11121, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (18, 42, 3797, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (18, 44, 7477, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (18, 46, 8703, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (18, 48, 9682, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (19, 42, 7421, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (19, 44, 8387, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (19, 46, 4209, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (19, 48, 3213, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (20, 42, 9021, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (20, 44, 9114, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (20, 46, 3815, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (20, 48, 7490, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (21, 30, 9122, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (21, 50, 10310, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (21, 100, 6850, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (22, 30, 9978, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (22, 50, 11324, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (22, 100, 8820, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (23, 30, 6515, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (23, 50, 10303, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (23, 100, 7917, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (24, 30, 7141, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (24, 50, 11636, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (24, 100, 8484, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (25, 42, 3528, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (25, 44, 11302, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (25, 46, 11393, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (25, 48, 10813, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (26, 30, 10542, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (26, 50, 6089, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (26, 100, 5219, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (27, 42, 6750, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (27, 44, 6782, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (27, 46, 8349, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (27, 48, 3869, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (28, 42, 8692, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (28, 44, 5646, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (28, 46, 10645, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (28, 48, 7436, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (29, 42, 11419, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (29, 44, 8198, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (29, 46, 7816, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (29, 48, 11068, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (30, 30, 5447, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (30, 50, 10368, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (30, 100, 4103, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (31, 42, 3385, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (31, 44, 6709, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (31, 46, 10894, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (31, 48, 3556, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (32, 30, 10875, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (32, 50, 4917, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (32, 100, 4136, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (33, 30, 9648, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (33, 50, 7385, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (33, 100, 10459, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (34, 42, 10730, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (34, 44, 10572, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (34, 46, 4752, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (34, 48, 10516, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (35, 30, 5715, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (35, 50, 11696, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (35, 100, 11607, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (36, 30, 7079, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (36, 50, 6743, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (36, 100, 11038, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (37, 30, 3914, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (37, 50, 6546, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (37, 100, 6409, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (38, 30, 3275, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (38, 50, 10906, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (38, 100, 7919, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (39, 42, 7300, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (39, 44, 8556, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (39, 46, 5962, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (39, 48, 10659, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (40, 42, 11462, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (40, 44, 9363, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (40, 46, 5532, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (40, 48, 9092, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (41, 42, 4095, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (41, 44, 7035, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (41, 46, 3325, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (41, 48, 11427, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (42, 30, 9443, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (42, 50, 5187, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (42, 100, 7364, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (43, 42, 11307, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (43, 44, 9137, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (43, 46, 9805, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (43, 48, 11863, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (44, 30, 5502, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (44, 50, 3193, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (44, 100, 11023, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (45, 42, 11829, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (45, 44, 4656, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (45, 46, 4403, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (45, 48, 8464, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (46, 42, 7723, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (46, 44, 10264, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (46, 46, 9452, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (46, 48, 5986, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (47, 42, 10129, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (47, 44, 11340, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (47, 46, 11320, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (47, 48, 9558, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (48, 30, 4454, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (48, 50, 4719, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (48, 100, 5714, 'ml');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (49, 42, 6256, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (49, 44, 5887, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (49, 46, 3603, 'size');
INSERT INTO product_variants (product_id, value, price, unit) VALUES (49, 48, 9792, 'size');
INSERT INTO product_categories (product_id, category_id) VALUES (1, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (1, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (2, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (2, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (2, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (3, (SELECT id FROM categories WHERE name='new'));
INSERT INTO product_categories (product_id, category_id) VALUES (4, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (4, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (4, (SELECT id FROM categories WHERE name='new'));
INSERT INTO product_categories (product_id, category_id) VALUES (5, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (5, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (6, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (6, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (7, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (8, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (8, (SELECT id FROM categories WHERE name='new'));
INSERT INTO product_categories (product_id, category_id) VALUES (8, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (9, (SELECT id FROM categories WHERE name='new'));
INSERT INTO product_categories (product_id, category_id) VALUES (9, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (10, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (10, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (10, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (11, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (11, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (12, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (12, (SELECT id FROM categories WHERE name='new'));
INSERT INTO product_categories (product_id, category_id) VALUES (12, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (13, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (13, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (13, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (14, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (15, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (15, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (15, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (16, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (16, (SELECT id FROM categories WHERE name='new'));
INSERT INTO product_categories (product_id, category_id) VALUES (16, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (17, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (17, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (18, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (18, (SELECT id FROM categories WHERE name='new'));
INSERT INTO product_categories (product_id, category_id) VALUES (18, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (19, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (19, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (20, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (20, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (21, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (21, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (22, (SELECT id FROM categories WHERE name='new'));
INSERT INTO product_categories (product_id, category_id) VALUES (23, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (24, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (24, (SELECT id FROM categories WHERE name='new'));
INSERT INTO product_categories (product_id, category_id) VALUES (24, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (25, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (25, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (25, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (26, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (26, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (26, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (27, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (27, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (28, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (29, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (29, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (30, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (31, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (31, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (31, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (32, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (32, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (32, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (33, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (34, (SELECT id FROM categories WHERE name='new'));
INSERT INTO product_categories (product_id, category_id) VALUES (34, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (35, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (35, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (35, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (36, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (36, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (36, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (37, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (38, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (38, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (39, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (40, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (41, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (41, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (42, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (43, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (44, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (44, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (45, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (45, (SELECT id FROM categories WHERE name='luxury'));
INSERT INTO product_categories (product_id, category_id) VALUES (45, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (46, (SELECT id FROM categories WHERE name='popular'));
INSERT INTO product_categories (product_id, category_id) VALUES (47, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (48, (SELECT id FROM categories WHERE name='new'));
INSERT INTO product_categories (product_id, category_id) VALUES (48, (SELECT id FROM categories WHERE name='clothes'));
INSERT INTO product_categories (product_id, category_id) VALUES (49, (SELECT id FROM categories WHERE name='flower'));
INSERT INTO product_categories (product_id, category_id) VALUES (49, (SELECT id FROM categories WHERE name='bags'));
INSERT INTO product_categories (product_id, category_id) VALUES (49, (SELECT id FROM categories WHERE name='popular'));